### ISSUE TITLE
Exception due to closed content stream.

### ISSUE THREAD

**Issue by alejo-enix** [caldav4j/caldav4j#121]
## Reproduce

  - caldav4j version 1.0.0-SNAPSHOT
  - Bedework server version 3.13.1.
  - link to code failing: https://github.com/caldav4j/caldav4j-import/blob/5546fe1289262a22c02b41a900cb2b5345260a1b/src/test/java/org/osaf/caldav4j/methods/PutGetTest.java#L91

**Steps to reproduce the issue:**

In the **log4j2.xml** file located in src/test/resources modify the log level of com.github.caldav4j to DEBUG or TRACE:
```
<Logger name="com.github.caldav4j" level="TRACE">
	<AppenderRef ref="Console"/>
</Logger>
```
Execute the unit test `PutGetTest#testAddRemoveCalendarResource`.

The test fails because the method `MethodUtil#StatusToExceptions` previously closed the stream while converting the response entity into a String.

The stack trace is:
```
com.github.caldav4j.exceptions.CalDAV4JException: Error retrieving and parsing server response at /ucaldav/user/vbede/collection_changeme/DE916949-731D-4DAE-BA93-48A38B2B2030.ics
	at com.github.caldav4j.methods.HttpGetMethod.getResponseBodyAsCalendar(HttpGetMethod.java:83)
	at com.github.caldav4j.methods.PutGetTest.testAddRemoveCalendarResource(PutGetTest.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.io.IOException: Attempted read from closed stream.
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:165)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at sun.nio.cs.StreamDecoder.read0(StreamDecoder.java:127)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:112)
	at java.io.InputStreamReader.read(InputStreamReader.java:168)
	at java.io.FilterReader.read(FilterReader.java:65)
	at java.io.PushbackReader.read(PushbackReader.java:90)
	at net.fortuna.ical4j.data.UnfoldingReader.read(UnfoldingReader.java:153)
	at java.io.StreamTokenizer.read(StreamTokenizer.java:500)
	at java.io.StreamTokenizer.nextToken(StreamTokenizer.java:544)
	at net.fortuna.ical4j.data.CalendarParserImpl.nextToken(CalendarParserImpl.java:635)
	at net.fortuna.ical4j.data.CalendarParserImpl.nextToken(CalendarParserImpl.java:621)
	at net.fortuna.ical4j.data.CalendarParserImpl.assertToken(CalendarParserImpl.java:465)
	at net.fortuna.ical4j.data.CalendarParserImpl.skipNewLines(CalendarParserImpl.java:545)
	at net.fortuna.ical4j.data.CalendarParserImpl.assertToken(CalendarParserImpl.java:510)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:178)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:149)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:198)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:178)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:165)
	at com.github.caldav4j.methods.HttpGetMethod.getResponseBodyAsCalendar(HttpGetMethod.java:69)
	... 26 more

```

## I expect

The test passing regardless of the Logger level enabled in the **log4j2.xml** file.

## Instead

The test fails when I change the logging level.

**Comment by ioggstream** [comment]
@TheAntimist ideas about how to fix it?

**Comment by TheAntimist** [comment]
Let me look into this and get back to you. @alejo-enix @ioggstream

**Comment by TheAntimist** [comment]
I think I figured out the issue, the stream is being read twice. Let me see if there's a workaround for it.

**Comment by ioggstream** [comment]
Thanks @TheAntimist
