### ISSUE TITLE
Double calendar-date zone created

### ISSUE THREAD

**Issue by bugeaud** [caldav4j/caldav4j#74]
It appears that calendar-data element is doubled at generation.

Example with the following code :
```
    static CalendarQuery buildSelectTimeBoxedQuery(DateTime begin, DateTime end){
        // First we need a query place holder
        final CalendarQuery query = new CalendarQuery();
                
        // Then, we request display of the ETag
	query.addProperty(CalDAVConstants.DNAME_GETETAG);
        
        // We request display VCALENDAR / VEVENT components
        final Comp vCalendarComp = new Comp(Calendar.VCALENDAR);
        final Comp vEventComp = new Comp("VEVENT");
        
        // With the following properties fetched
        vEventComp.addProp(new CalDAVProp("UID", false, false));
        vEventComp.addProp(new CalDAVProp("DTSTART", false, false));
        vEventComp.addProp(new CalDAVProp("DTEND", false, false));
        vEventComp.addProp(new CalDAVProp("ATTENDEE", false, false));
        
        // Add component to the parent
        vCalendarComp.addComp(vEventComp);
        
        // Indicate the expansion requested so that recuring event will be returned
        // as discrete events of the correct time frame (less burden on client side)
        final CalendarData calendarData = new CalendarData();        
        calendarData.setExpandOrLimitRecurrenceSet(CalendarData.EXPAND);
        calendarData.setRecurrenceSetStart(begin);
        calendarData.setRecurrenceSetEnd(end);
    
        // Set the selected component to the calendar's data 
        calendarData.setComp(vCalendarComp);
		
        // Search for VCALENDAR / VEVENT in the matching period
        final CompFilter vCalendarCompFilter = new CompFilter(Calendar.VCALENDAR);
        final CompFilter vEventCompFilter = new CompFilter("VEVENT",false,begin,end,null,null);
        vCalendarCompFilter.addCompFilter(vEventCompFilter);
        
        // Check that no attendee is there already. So only list events available for booking.
        final PropFilter attendeeIsNotDefined = new PropFilter("ATTENDEE",false,null,null,null,false,null,null,null);
        vEventCompFilter.addPropFilter(attendeeIsNotDefined);

        // Set the query to apply the filter & return the expected data
        query.setCalendarDataProp(calendarData);
        query.setCompFilter(vCalendarCompFilter);
       
        return query;
    }

CalendarQuery calendarQuery = buildSelectTimeBoxedQuery(new DateTime("20180524T070000Z"), new DateTime("20180528T200000Z"));
```
The result XML Query would be :
```
 <?xml version="1.0" encoding="UTF-8" standalone="no"?>
<C:calendar-query xmlns:C="urn:ietf:params:xml:ns:caldav">
	<D:prop xmlns:D="DAV:">
		<D:getetag/>
		<C:calendar-data>
			<C:comp name="VCALENDAR">
				<C:comp name="VEVENT">
					<C:prop name="UID"/>
					<C:prop name="DTSTART"/>
					<C:prop name="DTEND"/>
					<C:prop name="ATTENDEE"/>
				</C:comp>
			</C:comp>
			<C:expand end="20180528T200000Z" start="20180524T070000Z"/>
		</C:calendar-data>
		<C:calendar-data>
			<C:comp name="VCALENDAR">
				<C:comp name="VEVENT">
					<C:prop name="UID"/>
					<C:prop name="DTSTART"/>
					<C:prop name="DTEND"/>
					<C:prop name="ATTENDEE"/>
				</C:comp>
			</C:comp>
			<C:expand end="20180528T200000Z" start="20180524T070000Z"/>
		</C:calendar-data>
	</D:prop>
	<C:filter>
		<C:comp-filter name="VCALENDAR">
			<C:comp-filter name="VEVENT">
				<C:time-range end="20180528T200000Z" start="20180524T070000Z"/>
				<C:prop-filter name="ATTENDEE">
					<C:is-not-defined/>
				</C:prop-filter>
			</C:comp-filter>
		</C:comp-filter>
	</C:filter>
</C:calendar-query>
```

This double element will be an issue with servers. For instance Bedework will not fullfit the the expand clause if such a double element is found. Manual retrigger of the faulty HTTP request thru curl after removing the doubled element would result in a response working as expected.

**Comment by ioggstream** [comment]
Hi @bugeaud 

do you have this issue with the master/ branch?

Can you provide more info pls?

**Comment by TheAntimist** [comment]
I'll agree with what @ioggstream said. I ran the same code specifically:

     CalendarQuery calendarQuery = buildSelectTimeBoxedQuery(new DateTime("20180524T070000Z"), new DateTime("20180528T200000Z"));
     System.out.println(XMLUtils.prettyPrint(calendarQuery));

to get the following resultant output:

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<C:calendar-query xmlns:C="urn:ietf:params:xml:ns:caldav">
  <D:prop xmlns:D="DAV:">
    <D:getetag/>
    <C:calendar-data>
      <C:comp name="VCALENDAR">
        <C:comp name="VEVENT">
          <C:prop name="UID"/>
          <C:prop name="DTSTART"/>
          <C:prop name="DTEND"/>
          <C:prop name="ATTENDEE"/>
        </C:comp>
      </C:comp>
      <C:expand end="20180528T200000Z" start="20180524T070000Z"/>
    </C:calendar-data>
  </D:prop>
  <C:filter>
    <C:comp-filter name="VCALENDAR">
      <C:comp-filter name="VEVENT">
        <C:time-range end="20180528T200000Z" start="20180524T070000Z"/>
        <C:prop-filter name="ATTENDEE">
          <C:is-not-defined/>
        </C:prop-filter>
      </C:comp-filter>
    </C:comp-filter>
  </C:filter>
</C:calendar-query>
```

This was on the current master on maven with the only dependency as:

```
<dependency>
		  <groupId>com.github.caldav4j</groupId>
		  <artifactId>caldav4j</artifactId>
		  <version>0.9.1</version>
</dependency>
```

**Comment by bugeaud** [comment]
Thanks for you quick replies ;-)
As you anticipated I am using the latest version available on the repo.

I managed to workaround the issue with a workaround class :

```
public class CalendarQueryFixed extends CalendarQuery{
    
    private static final Logger LOGGER = Logger.getLogger( CalendarQueryFixed.class.getName() );
    
    
    protected Collection<XmlSerializable> cachedChildren;
    

    public CalendarQueryFixed(Prop properties, CompFilter compFilter, CalendarData calendarData, boolean allProp, boolean propName) {
        super(properties, compFilter, calendarData, allProp, propName);
    }

    public CalendarQueryFixed(DavPropertyNameSet properties, CompFilter compFilter, CalendarData calendarData, boolean allProp, boolean propName) {
        super(properties, compFilter, calendarData, allProp, propName);
    }

    public CalendarQueryFixed(Collection<? extends XmlSerializable> properties, CompFilter compFilter, CalendarData calendarData, boolean allProp, boolean propName) {
        super(properties, compFilter, calendarData, allProp, propName);
    }

    public CalendarQueryFixed(CompFilter compFilter, CalendarData calendarData, boolean allProp, boolean propName) {
        super(compFilter, calendarData, allProp, propName);
    }

    
    final Object lock = new Object();
    
    @Override
    protected Collection<XmlSerializable> getChildren() {
        synchronized(lock){
            if(cachedChildren==null){
                LOGGER.info("CalendarQueryFixed fixing...");
                cachedChildren = super.getChildren();
                LOGGER.info("CalendarQueryFixed cached set");
            }
        }
        LOGGER.info("CalendarQueryFixed returning cached");
        return cachedChildren;
    }
    
}

```

This quick and dirty workaound ensure that the getChildren only build the children tree out of the object fields once.

Before that, it was called twice :
```
	at testcaldav1.CalendarQueryFixed.getChildren(CalendarQueryFixed.java:51)
	at org.osaf.caldav4j.xml.OutputsDOMBase.fillElement(OutputsDOMBase.java:149)
	at org.osaf.caldav4j.xml.OutputsDOMBase.toXml(OutputsDOMBase.java:130)
	at org.osaf.caldav4j.xml.OutputsDOMBase.createNewDocument(OutputsDOMBase.java:109)
	at org.osaf.caldav4j.util.GenerateQuery.printQuery(GenerateQuery.java:518)
	at org.osaf.caldav4j.CalDAVCollection.getCalDAVResources(CalDAVCollection.java:1017)
	at org.osaf.caldav4j.CalDAVCollection.queryCalendars(CalDAVCollection.java:910)
	at testcaldav1.CalDavDemo1.main(CalDavDemo1.java:206)
```
and :
```
	at testcaldav1.CalendarQueryFixed.getChildren(CalendarQueryFixed.java:51)
	at org.osaf.caldav4j.xml.OutputsDOMBase.fillElement(OutputsDOMBase.java:149)
	at org.osaf.caldav4j.xml.OutputsDOMBase.toXml(OutputsDOMBase.java:130)
	at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.setRequestBody(DavMethodBase.java:204)
	at org.osaf.caldav4j.methods.CalDAVReportMethod.processReportRequest(CalDAVReportMethod.java:91)
	at org.osaf.caldav4j.methods.CalDAVReportMethod.<init>(CalDAVReportMethod.java:81)
	at org.osaf.caldav4j.methods.CalDAVReportMethod.<init>(CalDAVReportMethod.java:68)
	at org.osaf.caldav4j.methods.CalDAV4JMethodFactory.createCalDAVReportMethod(CalDAV4JMethodFactory.java:212)
	at org.osaf.caldav4j.CalDAVCollection.getCalDAVResources(CalDAVCollection.java:1023)
	at org.osaf.caldav4j.CalDAVCollection.queryCalendars(CalDAVCollection.java:910)
	at testcaldav1.CalDavDemo1.main(CalDavDemo1.java:206)

```

getChildren() look the same in the latest code. So I anticipate there is something in one or the other callstack related code that was changed in order to prevent it from beeing called twice.

I'll check on latest version how it behaves and if fixed try to identify what has been changed and update this issue accordingly.

FYI, my testcaldav1 (a REPORT with expand for recuring filtering out event with attendee) is still failing. A curl for a given period on my test server returning 4 event (2 expanded from the same repetitive and two other) with a curl from the exact request generated by caldav4j will only return 3 event. Only one of the two expanded is present. I anticipate there might be some issue regarding the unicity of UID. But I am not sure whose fault is it : calda4j, bedework or jackrabit. I'll open an issue at the correct location once I've found the "culprit".

**Comment by TheAntimist** [comment]
I was finally able to reproduce it. I will push a commit to fix it soon. But simply put, it's an issue if the same query is used more than once. I will push a commit soon to fix it.
