### ISSUE TITLE
Caldav query not filtering the events for ATTENDED property ?

### ISSUE THREAD

**Issue by signalarun** [caldav4j/caldav4j#82]
## Reproduce
 caldav4j version 0.9.1
 Server name : SOGo Version : v4 | url : https://sogo.nu/
```     
     public void getAllEventsForAttendeeByFilterProperties(String start, String end, String properties) {
        	try {
        		final String VEVENT_PROPERTIES_BY_TIMERANGE_C;
        		GenerateQuery queryGenerator;
        		
        		final String VEVENT_PROPERTIES_BY_TIMERANGE_F = "VEVENT [" + start + ";" + end + "]";
        		//final String VEVENT_PROPERTIES_BY_TIMERANGE_F = "VEVENT : ATTENDEE==mailto:alice@acme.com";
        		if(properties.isEmpty()) {
        			VEVENT_PROPERTIES_BY_TIMERANGE_C = "VEVENT";
        			//VEVENT_PROPERTIES_BY_TIMERANGE_C = "VEVENT : UID,DTSTART,DTEND,RRULE,RDATE,DURATION,EXRULE,EXDATE,RECURRENCE-ID,ATTENDEE";	
        		}else {
        			VEVENT_PROPERTIES_BY_TIMERANGE_C = "VEVENT : " + properties;
        		}
    			
    			queryGenerator = new GenerateQuery(VEVENT_PROPERTIES_BY_TIMERANGE_C, VEVENT_PROPERTIES_BY_TIMERANGE_F);
        
    			CalendarQuery calendarQuery = queryGenerator.generate();
    			
                ParamFilter paramSentBy = new ParamFilter();
                paramSentBy.setName("PARTSTAT");
                paramSentBy.setTextMatch(new TextMatch(null, null, null, "NEEDS-ACTION"));
                
                PropFilter propertyFilter = new PropFilter();
                propertyFilter.setName("ATTENDEE");
                propertyFilter.setTextMatch(new TextMatch(null, null, null, "mailto:alice@acme.com"));
                calendarQuery.getCompFilter().getCompFilters().get(0).addPropFilter(propertyFilter);
                
    			   calendarQuery.getCompFilter().getCompFilters().get(0) 
    			    .getPropFilters().get(0).addParamFilter(paramSentBy); 
    			   
    			   
    			
    			
    			System.out.println(printQuery(calendarQuery));
    			
    			List<Calendar>calendars = caldavCollection.queryCalendars(getHttpClient(), calendarQuery);

    			for (Calendar calendar : calendars) {
    			  if(calendar != null) {
    			  ComponentList componentList = calendar.getComponents().getComponents(Component.VEVENT);
    			  Iterator<VEvent> eventIterator = componentList.iterator();
    			  while (eventIterator.hasNext()) {
    			    VEvent ve = eventIterator.next();
    			    System.out.println("Event: "+ ve.toString());
    			    //System.out.println("Duration (h): "+ String.format("%.2f", calcDuration(ve)));
    			    System.out.println("\n\n");
    			  }
    			  }
    			}
        		
        		
    		} catch (CalDAV4JException e) {
    			e.printStackTrace();
    		} 
        }
```
Console Output :
```
117 [main] INFO net.fortuna.ical4j.util.Configurator - ical4j.properties not found.
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<C:calendar-query xmlns:C="urn:ietf:params:xml:ns:caldav">
  <D:prop xmlns:D="DAV:">
    <D:getetag/>
    <D:allprop/>
    <C:calendar-data>
      <C:comp name="VCALENDAR">
        <C:comp name="VEVENT"/>
      </C:comp>
    </C:calendar-data>
  </D:prop>
  <C:filter>
    <C:comp-filter name="VCALENDAR">
      <C:comp-filter name="VEVENT">
        <C:time-range end="20181101T000000Z" start="20180701T000000Z"/>
        <C:prop-filter name="ATTENDEE">
          <C:text-match collation="i;ascii-casemap">mailto:alice@acme.com</C:text-match>
          <C:param-filter name="PARTSTAT">
            <C:text-match collation="i;ascii-casemap">NEEDS-ACTION</C:text-match>
          </C:param-filter>
        </C:prop-filter>
      </C:comp-filter>
    </C:comp-filter>
  </C:filter>
</C:calendar-query>

net.fortuna.ical4j.data.ParserException: Error at line 1:Expected [BEGIN], read [20180828T103000Z]
	at net.fortuna.ical4j.data.CalendarParserImpl.assertToken(CalendarParserImpl.java:518)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:178)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:149)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:198)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:178)
	at org.osaf.caldav4j.model.response.CalendarDataProperty.getCalendarfromProperty(CalendarDataProperty.java:80)
	at org.osaf.caldav4j.model.response.CalendarDataProperty.getCalendarfromResponse(CalendarDataProperty.java:98)
	at org.osaf.caldav4j.CalDAVResource.<init>(CalDAVResource.java:39)
	at org.osaf.caldav4j.CalDAVCollection.getCalDAVResources(CalDAVCollection.java:1040)
	at org.osaf.caldav4j.CalDAVCollection.queryCalendars(CalDAVCollection.java:910)
	at org.cdac.krc.calendar.AcsoftCalendar.getAllEventsForAttendeeByFilterProperties(AcsoftCalendar.java:486)
	at CalendarApp.main(CalendarApp.java:161)
```
## I expect
 Events of given attendee.
## Instead
 Fetches all the events in the time range

note : Filtering works for UID property.

**Comment by TheAntimist** [comment]
@signalarun Can you confirm that this is not a server issue? Also, server details would be appreciated.

**Comment by TheAntimist** [comment]
On the http4client-dev branch, this should be used: `org.apache.http.wire` instead of `httpclient.wire`. For further info, [here](https://hc.apache.org/httpcomponents-client-ga/logging.html)

Although, for master that faq should still hold, due to the use of the HttpClient 3.x

**Comment by signalarun** [comment]
@ioggstream  I have modified the post as per the format.

**Comment by TheAntimist** [comment]
Can you fetch the httpclient wire details as described here: https://github.com/caldav4j/caldav4j/wiki/FAQ.md#faq-8

Or here: https://hc.apache.org/httpclient-3.x/logging.html

**Comment by ioggstream** [comment]
@signalarun it could either be that the server doesn't support:

  - ATTENDEE search
  - ATTENDEE + PARTSTAT

moreover in the code I see an exception: why is that?

**Comment by signalarun** [comment]
@TheAntimist I have added the log4j2. But nothing is logged upon running.

**Comment by signalarun** [comment]
@ioggstream when I traced through code, in the initial iteration of List<response> from server parser encounters with something which it doesnt recognise, the on second iteration it continues with output.
These are actually happening in library.

**Comment by TheAntimist** [comment]
Can you provide those logs as well, without knowing the specifics, we can only guess at the issue.

**Comment by signalarun** [comment]
@TheAntimist Nothing is getting logged!I think I shall create a repo and share the code.

**Comment by TheAntimist** [comment]
Sure or a gist would work as well

**Comment by pvtra96** [comment]
final String VEVENT_PROPERTIES_BY_TIMERANGE_F = "VEVENT [" + start + ";" + end + "]"; 
=> qg.setFilter("VEVENT [start;end] : UID==value1 , DTSTART==[start;end],DESCRIPTION==UNDEF, SUMMARY!=not my summary,")
You can edit this.
