### ISSUE TITLE
Create a CI with CircleCI

### ISSUE THREAD

**Issue by ioggstream** [caldav4j/caldav4j#94]
## I Wish

  - to move from Travis to CircleCI
  - to allow local Integration Tests with [`circleci build`](https://circleci.com/docs/2.0/local-cli/)

## Notes

  - [circleci local](https://circleci.com/docs/2.0/local-cli/)

**Comment by ioggstream** [comment]
@TheAntimist I was able to run some tests via circleci vs bedework. I got some errors - mainly `java.lang.IllegalArgumentException: Host name may not be empty`.

Do you have a clue? 

```
java.lang.IllegalArgumentException: Host name may not be empty
        at com.github.caldav4j.FunTest.setUp(FunTest.java:50)

[ERROR] testFun(com.github.caldav4j.FunTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException
        at com.github.caldav4j.FunTest.tearDown(FunTest.java:57)

[INFO] Running com.github.caldav4j.CalDAVCollectionTest
[ERROR] Tests run: 25, Failures: 0, Errors: 22, Skipped: 3, Time elapsed: 0.252 s <<< FAILURE! - in com.github.caldav4j.CalDAVCollectionTest
[ERROR] testAdd(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.138 s  <<< ERROR!
java.lang.IllegalArgumentException: Host name may not be empty
        at com.github.caldav4j.CalDAVCollectionTest.setUp(CalDAVCollectionTest.java:73)

[ERROR] testAdd(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.139 s  <<< ERROR!
java.lang.NullPointerException
        at com.github.caldav4j.CalDAVCollectionTest.tearDown(CalDAVCollectionTest.java:88)

[ERROR] testUpdateEvent(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.01 s  <<< ERROR!
java.lang.IllegalArgumentException: Host name may not be empty
        at com.github.caldav4j.CalDAVCollectionTest.setUp(CalDAVCollectionTest.java:73)

[ERROR] testUpdateEvent(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.01 s  <<< ERROR!
java.lang.NullPointerException
        at com.github.caldav4j.CalDAVCollectionTest.tearDown(CalDAVCollectionTest.java:88)

[ERROR] testReportCalendarWithTimezone(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.013 s  <<< ERROR!
java.lang.IllegalArgumentException: Host name may not be empty
        at com.github.caldav4j.CalDAVCollectionTest.setUp(CalDAVCollectionTest.java:73)

[ERROR] testReportCalendarWithTimezone(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.013 s  <<< ERROR!
java.lang.NullPointerException
        at com.github.caldav4j.CalDAVCollectionTest.tearDown(CalDAVCollectionTest.java:88)

[ERROR] testMultigetCalendar(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.009 s  <<< ERROR!
java.lang.IllegalArgumentException: Host name may not be empty
        at com.github.caldav4j.CalDAVCollectionTest.setUp(CalDAVCollectionTest.java:73)

[ERROR] testMultigetCalendar(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.01 s  <<< ERROR!
java.lang.NullPointerException
        at com.github.caldav4j.CalDAVCollectionTest.tearDown(CalDAVCollectionTest.java:88)

[ERROR] testGetWithoutCacheThenWithCache(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.022 s  <<< ERROR!
java.lang.IllegalArgumentException: Host name may not be empty
        at com.github.caldav4j.CalDAVCollectionTest.setUp(CalDAVCollectionTest.java:73)

[ERROR] testGetWithoutCacheThenWithCache(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.022 s  <<< ERROR!
java.lang.NullPointerException
        at com.github.caldav4j.CalDAVCollectionTest.tearDown(CalDAVCollectionTest.java:88)

[ERROR] getHref(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.007 s  <<< ERROR!
java.lang.IllegalArgumentException: Host name may not be empty
        at com.github.caldav4j.CalDAVCollectionTest.setUp(CalDAVCollectionTest.java:73)

[ERROR] getHref(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.007 s  <<< ERROR!
java.lang.NullPointerException
        at com.github.caldav4j.CalDAVCollectionTest.tearDown(CalDAVCollectionTest.java:88)

[ERROR] testAddNewRemove(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.012 s  <<< ERROR!
java.lang.IllegalArgumentException: Host name may not be empty
        at com.github.caldav4j.CalDAVCollectionTest.setUp(CalDAVCollectionTest.java:73)

[ERROR] testAddNewRemove(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.012 s  <<< ERROR!
java.lang.NullPointerException
        at com.github.caldav4j.CalDAVCollectionTest.tearDown(CalDAVCollectionTest.java:88)

[ERROR] testGetEventResources(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.006 s  <<< ERROR!
java.lang.IllegalArgumentException: Host name may not be empty
        at com.github.caldav4j.CalDAVCollectionTest.setUp(CalDAVCollectionTest.java:73)

[ERROR] testGetEventResources(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.006 s  <<< ERROR!
java.lang.NullPointerException
        at com.github.caldav4j.CalDAVCollectionTest.tearDown(CalDAVCollectionTest.java:88)

[ERROR] testTestConnection(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.006 s  <<< ERROR!
java.lang.IllegalArgumentException: Host name may not be empty
        at com.github.caldav4j.CalDAVCollectionTest.setUp(CalDAVCollectionTest.java:73)

[ERROR] testTestConnection(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.006 s  <<< ERROR!
java.lang.NullPointerException
        at com.github.caldav4j.CalDAVCollectionTest.tearDown(CalDAVCollectionTest.java:88)

[ERROR] queryCalendar(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.013 s  <<< ERROR!
java.lang.IllegalArgumentException: Host name may not be empty
        at com.github.caldav4j.CalDAVCollectionTest.setUp(CalDAVCollectionTest.java:73)

[ERROR] queryCalendar(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.014 s  <<< ERROR!
java.lang.NullPointerException
        at com.github.caldav4j.CalDAVCollectionTest.tearDown(CalDAVCollectionTest.java:88)

[ERROR] testGetCalendarByPath(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.009 s  <<< ERROR!
java.lang.IllegalArgumentException: Host name may not be empty
        at com.github.caldav4j.CalDAVCollectionTest.setUp(CalDAVCollectionTest.java:73)

[ERROR] testGetCalendarByPath(com.github.caldav4j.CalDAVCollectionTest)  Time elapsed: 0.009 s  <<< ERROR!
java.lang.NullPointerException
        at com.github.caldav4j.CalDAVCollectionTest.tearDown(CalDAVCollectionTest.java:88)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR] com.github.caldav4j.ACLCalDAVCollectionTest.getFolderAces(com.github.caldav4j.ACLCalDAVCollectionTest)
[ERROR]   Run 1: ACLCalDAVCollectionTest.setUp:41->BaseTestCase.setUp:57 » IllegalArgument Host...
[ERROR]   Run 2: ACLCalDAVCollectionTest.tearDown:47 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.ACLCalDAVCollectionTest.getResourceAces(com.github.caldav4j.ACLCalDAVCollectionTest)
[ERROR]   Run 1: ACLCalDAVCollectionTest.setUp:41->BaseTestCase.setUp:57 » IllegalArgument Host...
[ERROR]   Run 2: ACLCalDAVCollectionTest.tearDown:47 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.CalDAVCollectionTest.getHref(com.github.caldav4j.CalDAVCollectionTest)
[ERROR]   Run 1: CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 » IllegalArgument Host na...
[ERROR]   Run 2: CalDAVCollectionTest.tearDown:88 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.CalDAVCollectionTest.queryCalendar(com.github.caldav4j.CalDAVCollectionTest)
[ERROR]   Run 1: CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 » IllegalArgument Host na...
[ERROR]   Run 2: CalDAVCollectionTest.tearDown:88 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.CalDAVCollectionTest.testAdd(com.github.caldav4j.CalDAVCollectionTest)
[ERROR]   Run 1: CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 » IllegalArgument Host na...
[ERROR]   Run 2: CalDAVCollectionTest.tearDown:88 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.CalDAVCollectionTest.testAddNewRemove(com.github.caldav4j.CalDAVCollectionTest)
[ERROR]   Run 1: CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 » IllegalArgument Host na...
[ERROR]   Run 2: CalDAVCollectionTest.tearDown:88 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.CalDAVCollectionTest.testGetCalendarByPath(com.github.caldav4j.CalDAVCollectionTest)
[ERROR]   Run 1: CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 » IllegalArgument Host na...
[ERROR]   Run 2: CalDAVCollectionTest.tearDown:88 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.CalDAVCollectionTest.testGetEventResources(com.github.caldav4j.CalDAVCollectionTest)
[ERROR]   Run 1: CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 » IllegalArgument Host na...
[ERROR]   Run 2: CalDAVCollectionTest.tearDown:88 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.CalDAVCollectionTest.testGetWithoutCacheThenWithCache(com.github.caldav4j.CalDAVCollectionTest)
[ERROR]   Run 1: CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 » IllegalArgument Host na...
[ERROR]   Run 2: CalDAVCollectionTest.tearDown:88 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.CalDAVCollectionTest.testMultigetCalendar(com.github.caldav4j.CalDAVCollectionTest)
[ERROR]   Run 1: CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 » IllegalArgument Host na...
[ERROR]   Run 2: CalDAVCollectionTest.tearDown:88 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.CalDAVCollectionTest.testReportCalendarWithTimezone(com.github.caldav4j.CalDAVCollectionTest)
[ERROR]   Run 1: CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 » IllegalArgument Host na...
[ERROR]   Run 2: CalDAVCollectionTest.tearDown:88 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.CalDAVCollectionTest.testTestConnection(com.github.caldav4j.CalDAVCollectionTest)
[ERROR]   Run 1: CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 » IllegalArgument Host na...
[ERROR]   Run 2: CalDAVCollectionTest.tearDown:88 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.CalDAVCollectionTest.testUpdateEvent(com.github.caldav4j.CalDAVCollectionTest)
[ERROR]   Run 1: CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 » IllegalArgument Host na...
[ERROR]   Run 2: CalDAVCollectionTest.tearDown:88 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.FunTest.testFun(com.github.caldav4j.FunTest)
[ERROR]   Run 1: FunTest.setUp:50->BaseTestCase.setUp:57 » IllegalArgument Host name may not be...
[ERROR]   Run 2: FunTest.tearDown:57 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.methods.CalDAVReportTest.printCalendarQuery(com.github.caldav4j.methods.CalDAVReportTest)
[ERROR]   Run 1: CalDAVReportTest.setUp:74->BaseTestCase.setUp:57 » IllegalArgument Host name m...
[ERROR]   Run 2: CalDAVReportTest.tearDown:81 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.methods.CalDAVReportTest.queryPartialCalendar(com.github.caldav4j.methods.CalDAVReportTest)
[ERROR]   Run 1: CalDAVReportTest.setUp:74->BaseTestCase.setUp:57 » IllegalArgument Host name m...
[ERROR]   Run 2: CalDAVReportTest.tearDown:81 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.methods.CalDAVReportTest.testFreeBusyQuery(com.github.caldav4j.methods.CalDAVReportTest)
[ERROR]   Run 1: CalDAVReportTest.setUp:74->BaseTestCase.setUp:57 » IllegalArgument Host name m...
[ERROR]   Run 2: CalDAVReportTest.tearDown:81 » NullPointer
[INFO] 
[ERROR]   MkCalendarTest.setUp:58 » IllegalArgument Host name may not be empty
[ERROR]   MkCalendarTest.setUp:58 » IllegalArgument Host name may not be empty
[ERROR] com.github.caldav4j.methods.NewPropFindTest.basicTest(com.github.caldav4j.methods.NewPropFindTest)
[ERROR]   Run 1: NewPropFindTest.setUp:59->BaseTestCase.setUp:57 » IllegalArgument Host name ma...
[ERROR]   Run 2: NewPropFindTest.tearDown:65 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.methods.NewPropFindTest.testGetAcl(com.github.caldav4j.methods.NewPropFindTest)
[ERROR]   Run 1: NewPropFindTest.setUp:59->BaseTestCase.setUp:57 » IllegalArgument Host name ma...
[ERROR]   Run 2: NewPropFindTest.tearDown:65 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.methods.PutGetTest.testAddRemoveCalendarResource(com.github.caldav4j.methods.PutGetTest)
[ERROR]   Run 1: PutGetTest.setUp:55->BaseTestCase.setUp:57 » IllegalArgument Host name may not...
[ERROR]   Run 2: PutGetTest.tearDown:66 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.methods.PutGetTest.testPutNonLatin(com.github.caldav4j.methods.PutGetTest)
[ERROR]   Run 1: PutGetTest.setUp:55->BaseTestCase.setUp:57 » IllegalArgument Host name may not...
[ERROR]   Run 2: PutGetTest.tearDown:66 » NullPointer
[INFO] 
[ERROR] com.github.caldav4j.methods.PutGetTest.testResourceBundle(com.github.caldav4j.methods.PutGetTest)
[ERROR]   Run 1: PutGetTest.setUp:55->BaseTestCase.setUp:57 » IllegalArgument Host name may not...
[ERROR]   Run 2: PutGetTest.tearDown:66 » NullPointer
[INFO] 
[INFO] 
[ERROR] Tests run: 68, Failures: 0, Errors: 24, Skipped: 16

```

**Comment by TheAntimist** [comment]
That's odd, seems to be an issue with this: https://github.com/caldav4j/caldav4j/blob/24e75b30c6bb6df3f1aa81059dfd2c2997e3a8ed/src/test/java/com/github/caldav4j/BaseTestCase.java#L44

Can you replace that line, with a manual string and check?

**Comment by TheAntimist** [comment]
I just now ran this, on a clean cloned master:
```bash
mvn package -Dcaldav4jUri="http://testuser:testuser@localhost/cal.php/calendars/testuser/"
```

And got no issues on the tests, and the build was successful. Also note, I am using Baikal, but that should not make any difference.

Can you check if there's any issues with the username and password? I have had issues with usernames contains "@"

**Comment by ioggstream** [comment]
Different errors with baikal... commit is ead33d259b9fb2b03a9623624ff52f2d1c74111e.

**Comment by ioggstream** [comment]
On bedework I got

```
[ERROR] Failures: 
[ERROR]   ACLCalDAVCollectionTest.setUp:41->BaseTestCase.setUp:57 Response status expected:<201> but was:<403>
[ERROR]   ACLCalDAVCollectionTest.setUp:41->BaseTestCase.setUp:57 Response status expected:<201> but was:<403>
[ERROR]   CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 Response status expected:<201> but was:<403>
[ERROR]   CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 Response status expected:<201> but was:<403>
[ERROR]   CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 Response status expected:<201> but was:<403>
[ERROR]   CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 Response status expected:<201> but was:<403>
[ERROR]   CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 Response status expected:<201> but was:<403>
[ERROR]   CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 Response status expected:<201> but was:<403>
[ERROR]   CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 Response status expected:<201> but was:<403>
[ERROR]   CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 Response status expected:<201> but was:<403>
[ERROR]   CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 Response status expected:<201> but was:<403>
[ERROR]   CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 Response status expected:<201> but was:<403>
[ERROR]   CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 Response status expected:<201> but was:<403>
[ERROR]   FunTest.setUp:50->BaseTestCase.setUp:57 Response status expected:<201> but was:<403>
[ERROR]   CalDAVReportTest.setUp:74->BaseTestCase.setUp:57 Response status expected:<201> but was:<403>
[ERROR]   CalDAVReportTest.setUp:74->BaseTestCase.setUp:57 Response status expected:<201> but was:<403>
[ERROR]   CalDAVReportTest.setUp:74->BaseTestCase.setUp:57 Response status expected:<201> but was:<403>
[ERROR]   MkCalendarTest.testCreateRemoveCalendarCollection:127 Status code for mk: expected:<201> but was:<403>
```

**Comment by TheAntimist** [comment]
Hmm, that's an HTTP Forbidden error, could it be something with permissions? Any possibility that you debug the JUnit test, and verify? Or could you enable logging?

**Comment by ioggstream** [comment]
@TheAntimist I just wanted to be sure tests worked on your side.

I fixed baikal, the user was broken and instead of 4xx it returned 302.

Bedework needs a more indepth analysis though: if you want to give it a shot at that it would be great.

**Comment by TheAntimist** [comment]
Well, to confirm, the tests work on my side.

Do the tests work on on your Baikal setup?

I'll have to carve out some time for Bedework, can you open an issue for it? I'll take a look when I get time.

**Comment by ioggstream** [comment]
Baikal fine now. I'm trying to integrate it in circleci build to have a working flow.

**Comment by ioggstream** [comment]
Tests work fine running locally with baikal via `circleci build`. @TheAntimist you are welcome to test run this on your laptop. The only dependencies are:

  - docker
  - circleci local

Running on CircleCI throws the following error. It could be related to resource limitations (eg. limit the number of threads run by mvn..)

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project caldav4j: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/circleci/caldav4j/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/circleci/caldav4j && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Dfile.encoding=UTF-8 -jar /home/circleci/caldav4j/target/surefire/surefirebooter5796872116382193104.jar /home/circleci/caldav4j/target/surefire 2018-11-25T19-10-25_782-jvmRun1 surefire8908169173408113170tmp surefire_08893292748500719906tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/circleci/caldav4j && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Dfile.encoding=UTF-8 -jar /home/circleci/caldav4j/target/surefire/surefirebooter5796872116382193104.jar /home/circleci/caldav4j/target/surefire 2018-11-25T19-10-25_782-jvmRun1 surefire8908169173408113170tmp surefire_08893292748500719906tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1194)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1022)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:868)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] -> [Help 1]
[ERROR] 

```

**Comment by TheAntimist** [comment]
@ioggstream 

Attempted some fixes, for this build: https://circleci.com/gh/caldav4j/caldav4j/10

```
[ERROR] Failures: 
[ERROR]   ACLCalDAVCollectionTest.setUp:41->BaseTestCase.setUp:57 Response status expected:<201> but was:<405>
[ERROR]   ACLCalDAVCollectionTest.setUp:41->BaseTestCase.setUp:57 Response status expected:<201> but was:<405>
[ERROR]   CalDAVCollectionTest.setUp:73->BaseTestCase.setUp:57 Response status expected:<201> but was:<405>
[ERROR]   FunTest.tearDown:57 Response status expected:<204> but was:<404>
[ERROR]   CalDAVReportTest.setUp:74->BaseTestCase.setUp:57 Response status expected:<201> but was:<405>
[ERROR]   CalDAVReportTest.setUp:74->BaseTestCase.setUp:57 Response status expected:<201> but was:<405>
[ERROR]   MkCalendarTest.testCreateRemoveCalendarCollection:127 Status code for mk: expected:<201> but was:<405>
[ERROR]   NewPropFindTest.setUp:59->BaseTestCase.setUp:57 Response status expected:<201> but was:<405>
```

i.e. Method is not allowed.
